language: node_js
node_js:
  - "0.12"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5"
  - "6"
before_script:
  - npm install -g webpack
  - npm install -g gulp
  - npm install -g gulp-cli
  - npm install -g mocha